### ISSUE TITLE
Error: {"message":"Either resource not found or already deleted","status":"fail"}

### ISSUE THREAD

**Issue by joao-motork** [LambdaTest/wdio-lambdatest-service#54]
- Node version: v16.20.0
- wdio-lambdatest-service version: 2.0.0

For an mobile app test suite, every time I run a scenario, the following error is logged:
![image](https://github.com/LambdaTest/wdio-lambdatest-service/assets/132624270/9deb6630-5ae9-46d3-95f0-eef38249787c)

**Comment by Shahnawaz-Sk** [comment]
@joao-motork Can you please provide more details on the capabilities you are passing for the test ?

**Comment by joao-motork** [comment]
These are the capabilities:

[config.zip](https://github.com/LambdaTest/wdio-lambdatest-service/files/11509925/config.zip)

**Comment by deepanshusri** [comment]
hey @joao-motork , 
 Could you please help us with the API that you are using here?
Also, please share your email so that we can get in touch with you in order to fix this for you.

**Comment by edwinkcw** [comment]
I faced this problem too. This is due to when the service is going to update the status of the session using this API https://www.lambdatest.com/support/api-doc/?key=selenium-automation-api. This library is using LambdaRestClient https://github.com/LambdaTest/wdio-lambdatest-service/blob/27726ba13e50c4e2c98c2bfc61338128492bd914/src/service.js#L281

![Screen Shot 2023-06-15 at 11 13 47 AM](https://github.com/LambdaTest/wdio-lambdatest-service/assets/72035/58dae67c-8431-4b10-a4e5-fa0f33c4db00)

**Comment by deepanshusri** [comment]
Hi @joao-motork , please use below command in your conf.js file to run the project. That will resolve your issue.
**product:'appAutomation'**

For Edwin, I believe you are performing native app automation on the platform but using the selenium API here to update the status of the session. Hence, I would request you to use the Appium API 
<img width="554" alt="image" src="https://github.com/LambdaTest/wdio-lambdatest-service/assets/103935065/2c295112-e4b6-43ae-9d88-5d4c8fd808a0">

**Comment by joao-motork** [comment]
Closed. Suggest config fix the problem.
